# Generated by Django 3.1.4 on 2020-12-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prince',
            new_name='price',
        ),
    ]
