# Generated by Django 3.1.4 on 2020-12-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='costumer',
            new_name='customer',
        ),
    ]
